
public class ExceptionDemo1 
{
   
	public static void main(String[] args) 
	{
		int a=100;
		int b=3;
		int c=0;
		int d;
		try
		{
			d= a+b/c;
		}
		catch(Exception e)
		{
			System.out.println("Exception handled");
		}		
		finally                        // finally block always runs no matter the exception occurs or not
		{
			if(a==0)
				a=a+1;
			if(b==0)
				b=b+1;
			if(c==0)
				c=c+1;
			d=a+b/c;
			System.out.println(d);
		}
		
		System.out.println("Runs perfectly.");
	}

}
